package com.example.whatsopen

data class CountryInfo(val flag: String, val name: String)

val COUNTRY_DATA = mapOf(
    "1" to CountryInfo("🇺🇸", "United States"),
    "44" to CountryInfo("🇬🇧", "United Kingdom"),
    "91" to CountryInfo("🇮🇳", "India"),
    "86" to CountryInfo("🇨🇳", "China"),
    "81" to CountryInfo("🇯🇵", "Japan"),
    "49" to CountryInfo("🇩🇪", "Germany"),
    "33" to CountryInfo("🇫🇷", "France"),
    "39" to CountryInfo("🇮🇹", "Italy"),
    "7" to CountryInfo("🇷🇺", "Russia"),
    "55" to CountryInfo("🇧🇷", "Brazil"),
    "34" to CountryInfo("🇪🇸", "Spain"),
    "61" to CountryInfo("🇦🇺", "Australia"),
    "52" to CountryInfo("🇲🇽", "Mexico"),
    "82" to CountryInfo("🇰🇷", "South Korea"),
    "90" to CountryInfo("🇹🇷", "Turkey"),
    "31" to CountryInfo("🇳🇱", "Netherlands"),
    "966" to CountryInfo("🇸🇦", "Saudi Arabia"),
    "971" to CountryInfo("🇦🇪", "UAE"),
    "65" to CountryInfo("🇸🇬", "Singapore"),
    "92" to CountryInfo("🇵🇰", "Pakistan"),
    "351" to CountryInfo("🇵🇹", "Portugal"),
    "54" to CountryInfo("🇦🇷", "Argentina"),
    "20" to CountryInfo("🇪🇬", "Egypt"),
    "27" to CountryInfo("🇿🇦", "South Africa"),
    "30" to CountryInfo("🇬🇷", "Greece"),
    "32" to CountryInfo("🇧🇪", "Belgium"),
    "36" to CountryInfo("🇭🇺", "Hungary"),
    "40" to CountryInfo("🇷🇴", "Romania"),
    "41" to CountryInfo("🇨🇭", "Switzerland"),
    "43" to CountryInfo("🇦🇹", "Austria"),
    "45" to CountryInfo("🇩🇰", "Denmark"),
    "46" to CountryInfo("🇸🇪", "Sweden"),
    "47" to CountryInfo("🇳🇴", "Norway"),
    "48" to CountryInfo("🇵🇱", "Poland"),
    "51" to CountryInfo("🇵🇪", "Peru"),
    "53" to CountryInfo("🇨🇺", "Cuba"),
    "56" to CountryInfo("🇨🇱", "Chile"),
    "57" to CountryInfo("🇨🇴", "Colombia"),
    "58" to CountryInfo("🇻🇪", "Venezuela"),
    "60" to CountryInfo("🇲🇾", "Malaysia"),
    "62" to CountryInfo("🇮🇩", "Indonesia"),
    "63" to CountryInfo("🇵🇭", "Philippines"),
    "64" to CountryInfo("🇳🇿", "New Zealand"),
    "66" to CountryInfo("🇹🇭", "Thailand"),
    "84" to CountryInfo("🇻🇳", "Vietnam"),
    "93" to CountryInfo("🇦🇫", "Afghanistan"),
    "94" to CountryInfo("🇱🇰", "Sri Lanka"),
    "95" to CountryInfo("🇲🇲", "Myanmar"),
    "98" to CountryInfo("🇮🇷", "Iran"),
    "212" to CountryInfo("🇲🇦", "Morocco"),
    "213" to CountryInfo("🇩🇿", "Algeria"),
    "216" to CountryInfo("🇹🇳", "Tunisia"),
    "218" to CountryInfo("🇱🇾", "Libya"),
    "220" to CountryInfo("🇬🇲", "Gambia"),
    "234" to CountryInfo("🇳🇬", "Nigeria"),
    "254" to CountryInfo("🇰🇪", "Kenya"),
    "263" to CountryInfo("🇿🇼", "Zimbabwe"),
    "355" to CountryInfo("🇦🇱", "Albania"),
    "380" to CountryInfo("🇺🇦", "Ukraine"),
    "420" to CountryInfo("🇨🇿", "Czech Republic"),
    "421" to CountryInfo("🇸🇰", "Slovakia"),
    "886" to CountryInfo("🇹🇼", "Taiwan")
)
